    results_per_page: 100
    result_type: recent
    search_term: <the term you want to search for>
    twitter_timestamp: 61847783463854082 # the timestamp you want to start searching at
    api_endpoint_twitter: 'http://search.twitter.com/search.json'
    api_endpoint_tumblr: 'http://www.tumblr.com'
    tumblr_username: <your tumblr username / e-mail address>
    tumblr_password: <your tumblr password>
    update_period: 300 #check for updates every 300 secs = 5 minutes
    shouts: 'says' # will be concatenated after the username, before the message: @mr_x <shouts>: awesome things on a photo!
    whitelist: #twitter accounts in that list will have their tweets published immediately. post from others will be saved as drafts
      - whitey_mc_whitelist
      - sven_kr
