results_per_page: 100
result_type: recent
search_term: 'cat+dog+unicorn' #find tweets containing any of these terms
start_at_tweet_id: 61847783463854082 # the tweet id to start searching at
api_endpoint_twitter: 'http://search.twitter.com/search.json'
api_endpoint_tumblr: 'http://www.tumblr.com'
tumblr_oauth_api_key: YOUR APPS TUMBLR API TOKEN
tumblr_oauth_api_secret: YOUR APPS TUMBLR API SECRET
tumblr_oauth_access_token_key: YOUR BLOGS OAUTH ACCESS TOKEN KEY
tumblr_oauth_access_token_secret: YOUR BLOGS OAUTH ACCESS TOKEN SECRE
group: TUMBLR_GROUP_TO_POST_TO #e.g. mysubblog.tumblr.com
embedly_key: '' #tweetlr uses http://embedly.com for link processing. a free plan containing an api key is available & recommended to use in order to ensure full support
update_period: 300 #check for updates every 300 secs = 5 minutes
shouts: 'says' # will be concatenated after the username, before the message: @mr_x says: awesome things on a photo!
loglevel: 1 # 0: debug, 1: info (default), 2: warn, 3: error, 5: fatal
whitelist: #twitter accounts in that list will have their tweets published immediately. post from others will be saved as drafts. blank list will publish all tweets immediately
  - whitey_mc_whitelist
  - sven_kr